const char* quoteArray[] {
  "Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do. So throw off the bowlines. Sail away from the safe harbor. Catch the trade winds in your sails. Explore. Dream. Discover.;Mark Twain",
  "I can't understand why people are frightened of new ideas. I'm frightened of the old ones.;John Cage",
  "The tragedy of life is not so much what men suffer, but rather what they miss.;Thomas Carlyle",
  "The greatest mistake you can make in life is to be continually fearing you will make one.;Elbert Hubbard",
  "Anyone who has never made a mistake has never tried anything new.;Albert Einstein",
  "It's better to hang out with people better than you. Pick out associates whose behavior is better than yours and you'll drift in that direction.;Warren Buffett",
  "The question is not who is going to let me, it's who is going to stop me.;Ayn Rand",
  "The dumbest people I know are those who know it all.;Malcolm Forbes",
  "If what you're doing is not your passion, you have nothing to lose.;George Eliot",
  "The person who says something is impossible should not interrupt the person who is doing it.;",
  "Making the simple complicated is commonplace; making the complicated simple, awesomely simple, that's creativity.;Charles Mingus",
  "All our dreams can come true - if we have the courage to pursue them.;Walt Disney",
  "The best years of your life are the ones in which you decide your problems are your own. You do not blame them on your mother, the ecology, or the president. You realize that you control your own destiny.;Albert Ellis",
  "If opportunity doesn't knock, build a door.;Milton Berle",
  "Let us so live that when we come to die even the undertaker will be sorry.;Mark Twain",
  "A good traveler has no fixed plans, and is not intent on arriving.;Lao Tzu",
  "The World is a book, and those who do not travel read only a page.;Saint Augustine",
  "Once in a while it really hits people that they don't have to experience the world in the way they have been told to.;Alan Keightley",
  "The important thing is not being afraid to take a chance. Remember, the greatest failure is to not try. Once you find something you love to do, be the best at doing it.;Debbi Fields",
  "Be who you are and say what you feel, because those who mind don't matter, and those who matter don't mind.;Dr. Seuss",
  "Yesterday is history. Tomorrow is a mystery. Today is a gift. That's why we call it 'The Present'.;Eleanor Roosevelt",
  "Whenever you find yourself on the side of the majority, it is time to pause and reflect.;Mark Twain",
  "Money alone isn't enough to bring happiness... happiness [is] when you're actually truly ok with losing everything you have.;Tony Hsieh",
  "To live is the rarest thing in the world. Most people exist, that's all.;Oscar Wilde",
  "Don't wait. The time will never be just right.;Napoleon Hill",
  "Live as if you were to die tomorrow. Learn as if you were to live forever.;Mahatma Gandhi",
  "A year from now you may wish you had started today.;Karen Lamb",
  "Live simply, so others may simply live.;Mahatma Gandhi",
  "Perfection is achieved, not when there is nothing more to add, but when there is nothing left to take away.;Antoine de Saint-Exupery",
  "We act as though comfort and luxury were the chief requirements of life, when all that we need to make us happy is something to be enthusiastic about.;Albert Einstein",
  "The key to performance is elegance, not battalions of special cases.;Jon Bentley and Douglas McIlroy",
  "A desk is a dangerous place from which to view the world.;John Le Carre",
  "One machine can do the work of fifty ordinary men. No machine can do the work of one extraordinary man.;Elbert Hubbard",
  "Folks who never do any more than they are paid for, never get paid more than they do.;Elbert Hubbard",
  "The trouble in corporate America is that too many people with too much power live in a box (their home), then travel the same road every day to another box (their office).;Faith Popcorn",
  "We buy things we don't need with money we don't have to impress people we don't like.;David Ramsey",
  "It is hard to fail, but it is worse never to have tried to succeed.;Theodore Roosevelt",
  "Instead of wondering when your next vacation is, maybe you should set up a life you don't need to escape from.;Seth Godin",
  "It's a funny thing about life; if you refuse to accept anything but the best, you very often get it.;W. Somerset Maugham",
  "We make a fine bourbon, at a profit if we can, at a loss if we must, but always FINE BOURBON.;Pappy Van Winkle",
  "An army of lions led by a sheep is no match for an army of sheep led by a lion.;Winston Churchill",
  "A ship in port is safe, but that is not what ships are for. ;Grace Hopper",
  "I never let my schooling get in the way of my education;Mark Twain",
  "There are no traffic jams along the extra mile.;Roger Staubach",
  "The world is a dangerous place, not because of those who do evil, but because of those who look on and do nothing.;Albert Einstein",
  "Whatever you think you can do or believe you can do, begin it. Action has magic, grace and power in it.;Johann Wolfgang von Goethe",
  "Defeat is not the worst of failures.  Not to have tried is the true failure.;George Woodberry",
  "It is always the start that requires the greatest effort.;James Cash Penney ",
  "The best thinking has been done in solitude.;Thomas Edison",
  "If you will live like no one else, later you can live like no one else.;Dave Ramsey",
  "The harder I work, the luckier I get.;Samuel Goldwyn",
  "Life is not measured by the number of breaths we take, but by the moments that take our breath away.;Maya Angelou",
  "Never regret. If it's good, it's wonderful. If it's bad, it's experience.;Victoria Holt",
  "We are what we repeatedly do. Excellence, then is not an act but a habit.;Aristotle",
  "Happiness is not something you postpone for the future; it is something you design for the present.;Jim Rohn",
  "Don't make a decision based solely on popularity. Just because other people are doing it doesn't mean it's the best choice for you.;Anonymous",
  "Sometimes you need to be alone to reflect on life.  Take time out to take care of yourself.  You deserve it.;Anonymous",
  "One travels more usefully when alone, because he reflects more.;Thomas Jefferson",
  "We must all suffer one of two things: the pain of discipline or the pain of regret and disappointment.;Jim Rohn",
  "I haven't failed, I've just found 10,000 ways that don't work.;Thomas Alva Edison",
  "The three most harmful addictions are heroin, carbohydrates and a monthly salary.;Nassim Nicholas Taleb",
  "Never half-ass two things, whole-ass one thing.;Ron Swanson",
  "Humility is not thinking less of yourself, it's thinking of yourself less.;C. S. Lewis",
  "Every traveler has a home of his own, and he learns to appreciate it the more from his wandering.;Charles Dickens",
  "Study while others are sleeping; work while others are loafing; prepare while others are playing; and dream while others are wishing.;William A. Ward",
  "Nothing diminishes anxiety faster than action.;Walter Anderson",
  "If you don't design your own life plan, chances are you'll fall into someone else's plan.;Jim Rohn",
  "If you can solve your problem, then what is the need of worrying? If you cannot solve it, then what is the use of worrying?;Shantideva",
  "Sometimes life is going to hit you in the head with a brick. Don't lose faith.;Steve Jobs",
  "It takes as much energy to wish as it does to plan.;Eleanor Roosevelt",
  "I am so clever that sometimes I don't understand a single word of what I am saying.;Oscar Wilde",
  "Underpromise;overdeliver.;Tom Peters",
  "The world needs dreamers and the world needs doers. But above all, the world needs dreamers who do.;Sarah Ban Breathnach",
  "When you listen, it's amazing what you can learn. When you act on what you've learned, it's amazing what you can change.;A. McLaughlin",
  "Simplicity is the ultimate sophistication.;Leonardo Da Vinci",
  "They may forget what you said, but they will never forget how you made them feel.;Carl W. Buechner",
  "Be too busy to have time for regrets.;Angela Wright",
  "Don't spend time with anyone you don't like.;Prue Leith",
  "Work hard but make sure you enjoy life too.;Ted Smart",
  "You only get one crack at a big opportunity so make sure you recognize it and grab it with both hands.;Darren Richards",
  "The more reasons you have for achieving your goal, the more determined you will become.;Brian Tracy",
  "Nothing is really work unless you would rather be doing something else.;James M. Barrie",
  "The highest reward for a person's toil is not what they get for it, but what they become by it.;John Ruskin",
  "Pleasure in the job puts perfection in the work.;Aristotle",
  "Long-range goals keep you from being frustrated by short-term failures.;J. C. Penney",
  "Respond; don't react. Listen; don't talk. Think; don't assume.;Raji Lukkoor",
  "Do not fear going forward slowly; fear only to stand still.;Chinese Proverb",
  "Win without boasting. Lose without excuse.;Albert Payson",
  "Talent is cheaper than table salt. What separates the talented individual from the successful one is a lot of hard work.;Stephen King",
  "Don't re-open old wounds in order to examine their origins. Leave them healed.;Richard Bandler",
  "The act of taking the first step is what separates the winners from the losers.;Brian Tracy",
  "A goal should scare you a little, and excite you a lot.;Dr. Joe Vitale",
  "A person who won't read has no advantage over one who can't read.;Mark Twain",
  "It always seems impossible until it's done.;Nelson Mandela",
  "There is only one success - to be able to spend your life in your own way.;Christopher Morley",
  "Always and never are two words you should always remember never to use.;Wendell Johnson",
  "Don't find fault, find a remedy.;Henry Ford",
  "A man is a success if he gets up in the morning and goes to bed at night and in between does what he wants to do.;Bob Dylan",
  "A superior man is modest in his speech, but exceeds in his actions.;Confucious",
  "You cannot do a kindness too soon, for you never know how soon it will be too late.;Ralph Waldo Emerson"
};
